### ISSUE TITLE
Error: no bids on deployment

### ISSUE THREAD

**Issue by jatm80** [cloud-j-luna/terraform-provider-akash#24]
Deployment did not close after receiving no bids
```
akash_deployment.dpl: Creating...
akash_deployment.dpl: Still creating... [10s elapsed]
akash_deployment.dpl: Still creating... [20s elapsed]
akash_deployment.dpl: Still creating... [30s elapsed]
akash_deployment.dpl: Still creating... [40s elapsed]
akash_deployment.dpl: Still creating... [50s elapsed]
akash_deployment.dpl: Still creating... [1m0s elapsed]
akash_deployment.dpl: Still creating... [1m10s elapsed]
╷
│ Error: no bids on deployment
│ 
│   with akash_deployment.dpl,
│   on deployment.tf line 1, in resource "akash_deployment" "dpl":
│    1: resource "akash_deployment" "dpl" {
│ 
```

![image](https://user-images.githubusercontent.com/63689259/199469091-5b3ff66a-22d2-411d-9c12-50f16f69e60c.png)

**Comment by cloud-j-luna** [comment]
Thank you @jatm80 !
The issue here is on `resource_deployment.go` around line `190`:
```go
if len(bids) == 0 {
    return nil, diag.FromErr(errors.New("no bids on deployment"))
}
```

It should, similar to other stages of the deployment process, close the deployment in case there are no bids. Example:
```go
err := akash.DeleteDeployment(seqs.Dseq, akash.Config.AccountAddress)
if err != nil {
    return append(diagnostics, diag.FromErr(err)...)
}
```

Feel free to create a PR with this fix. 😄

**Comment by jatm80** [comment]
> Thank you @jatm80 ! The issue here is on `resource_deployment.go` around line `190`:
> 
> ```go
> if len(bids) == 0 {
>     return nil, diag.FromErr(errors.New("no bids on deployment"))
> }
> ```
> 
> It should, similar to other stages of the deployment process, close the deployment in case there are no bids. Example:
> 
> ```go
> err := akash.DeleteDeployment(seqs.Dseq, akash.Config.AccountAddress)
> if err != nil {
>     return append(diagnostics, diag.FromErr(err)...)
> }
> ```
> 
> Feel free to create a PR with this fix. smile

Awesome, thanks for the hint, i will give it a go this weekend and raise the PR
