### ISSUE TITLE
Multiple Deployments Opened and Then Eventual Failure

### ISSUE THREAD

**Issue by chainzero** [cloud-j-luna/terraform-provider-akash#25]
When `terraform apply` is executed - using an Akash SDL with a single service and count of 1 - multiple deployments are launched and eventually the execution fails with an `insufficient funds` message.

Essentially the provider is creating a deployment, when this deployment attempt fails another deployment is created, and this occurs repeatedly until the associated wallet is out of necessary funds.  The individual deployment creation attempts are successful - as many deployments exists following execution - but appear to fail in provider selection/manifest send and then move onto a new deployment attempt.

The TF and SDL files used are the examples provided in this doc:

https://docs.akash.network/other-resources/experimental/akash-deployments-via-terraform/akash-sdl-hello-world-example

Attaching debug from `terraform apply` from an example invoke.
[terraformLogsv1.txt](https://github.com/cloud-j-luna/terraform-provider-akash/files/9930019/terraformLogsv1.txt)

**Comment by cloud-j-luna** [comment]
To add to your issue, the return message when executing the deployment creation is:
```
Error: error unmarshalling result: unknown field "mempoolError" in types.ResponseCheckTx
```

Seems to be an issue related to the response from the Akash client.
